export type NetworkDirectoryMember = {
  id: string;
  name: string;
  category: string;
  location: string;
  instagram: string;
  instagramUrl: string;
  websiteUrl: string;
  description: string;
  profileImage?: string;
  imageAlt?: string;
  featured: boolean;
};

// Public projection of the private Creative Network submissions sheet.
// Keep email addresses, internal notes, and full submission text out of this file.
export const networkDirectoryMembers: NetworkDirectoryMember[] = [
  {
    "id": "grafik-21-andrew-wright",
    "name": "Andrew Wright / Grafik 2.1",
    "category": "Creative",
    "location": "Gateshead / Newcastle upon Tyne",
    "instagram": "@grafik2.1",
    "instagramUrl": "https://www.instagram.com/grafik2.1/",
    "websiteUrl": "https://www.grafiktwo.one",
    "description": "A visual creative and educator working principally with screen print and solar plate printmaking.",
    "featured": false
  },
  {
    "id": "alex-davis-art-vibes-newcastle",
    "name": "Alex Davis / Art Vibes Newcastle",
    "category": "Artist",
    "location": "Newcastle",
    "instagram": "Artvibesnewcastle",
    "instagramUrl": "https://www.instagram.com/Artvibesnewcastle/",
    "websiteUrl": "",
    "description": "A local graffiti artist creating work across the North East.",
    "featured": false
  },
  {
    "id": "alexei-crawley",
    "name": "Alexei Crawley",
    "category": "Musician",
    "location": "Newcastle",
    "instagram": "@alexeicrawley @SQUARMS",
    "instagramUrl": "https://www.instagram.com/alexeicrawley/",
    "websiteUrl": "https://alexei.studio",
    "description": "A touring performer and composer who also mentors developing musicians through practical, real-world experience.",
    "featured": false
  },
  {
    "id": "alice-stainthorpe",
    "name": "Alice Stainthorpe",
    "category": "Artist",
    "location": "Newcastle",
    "instagram": "@stainhead",
    "instagramUrl": "https://www.instagram.com/stainhead/",
    "websiteUrl": "",
    "description": "An illustrator and mural artist working across traditional and digital media, paint and aerosol.",
    "featured": false
  },
  {
    "id": "amanda-edmiston",
    "name": "Amanda Edmiston",
    "category": "Creative",
    "location": "Hexham",
    "instagram": "@amanda.edmiston",
    "instagramUrl": "https://www.instagram.com/amanda.edmiston/",
    "websiteUrl": "https://www.botanicafabula.co.uk",
    "description": "A writer, professional storyteller and artist whose background in herbal medicine informs intergenerational work about plants and place.",
    "featured": false
  },
  {
    "id": "amanda-jo",
    "name": "Amanda Jo",
    "category": "Artist",
    "location": "Wallsend",
    "instagram": "@thegeordie_artist @amandajo_skinartist",
    "instagramUrl": "https://www.instagram.com/thegeordie_artist/",
    "websiteUrl": "https://www.amandajo.co.uk",
    "description": "A multidisciplinary artist who experiments with different forms to keep developing her practice.",
    "featured": false
  },
  {
    "id": "amanda-mulholland",
    "name": "Amanda Mulholland",
    "category": "Creative",
    "location": "Newcastle",
    "instagram": "@tittle_the_brick",
    "instagramUrl": "https://www.instagram.com/tittle_the_brick/",
    "websiteUrl": "https://www.tittlethebrick.co.uk",
    "description": "A jeweller making one-of-a-kind pieces from recycled silver using traditional silversmithing methods.",
    "featured": false
  },
  {
    "id": "amelie-smith",
    "name": "Amelie Smith",
    "category": "Artist",
    "location": "County Durham, Bishop Auckland",
    "instagram": "@applesandstars",
    "instagramUrl": "https://www.instagram.com/applesandstars/",
    "websiteUrl": "https://applesandstars.co.uk/",
    "description": "A multimedia illustrator specialising in editorial and conceptual work inspired by film, television, music and pop culture.",
    "featured": false
  },
  {
    "id": "amy-richardson",
    "name": "Amy Richardson",
    "category": "Creative",
    "location": "Newcastle/North Shields",
    "instagram": "Muscari_uk",
    "instagramUrl": "https://www.instagram.com/Muscari_uk/",
    "websiteUrl": "https://muscarievents.co.uk",
    "description": "A floral designer at Harbour House in North Shields, creating modern arrangements for weddings, brand activations, supper clubs and photoshoots.",
    "featured": false
  },
  {
    "id": "andi-talbot",
    "name": "Andi Talbot",
    "category": "Photographer",
    "location": "Newcastle",
    "instagram": "@andichrist19",
    "instagramUrl": "https://www.instagram.com/andichrist19/",
    "websiteUrl": "",
    "description": "A photographer specialising in live events, including gigs and drag, alongside studio and location portraiture.",
    "featured": false
  },
  {
    "id": "andrew-miller",
    "name": "Andrew Miller",
    "category": "Personal trainer",
    "location": "South Shields",
    "instagram": "@demi_god_fitness",
    "instagramUrl": "https://www.instagram.com/demi_god_fitness/",
    "websiteUrl": "",
    "description": "Head coach at Demi God Fitness, a North East gym specialising in athletic performance.",
    "featured": false
  },
  {
    "id": "auburn-langley",
    "name": "Auburn Langley",
    "category": "Creative",
    "location": "Sunderland",
    "instagram": "@auburn_langley",
    "instagramUrl": "https://www.instagram.com/auburn_langley/",
    "websiteUrl": "https://www.sunderlandlitandphilsociety.com",
    "description": "A workshop leader bringing history to life through creative sessions on calligraphy, women’s history and more.",
    "featured": false
  },
  {
    "id": "bex-masters",
    "name": "Bex Masters",
    "category": "Artist",
    "location": "Newcastle",
    "instagram": "bexmastersart",
    "instagramUrl": "https://www.instagram.com/bexmastersart/",
    "websiteUrl": "https://bexmasters.com",
    "description": "A Scottish Indian visual artist based in Newcastle, working across painting, murals, gilding, bookbinding, modelling and arts education.",
    "featured": false
  },
  {
    "id": "brandon-turner",
    "name": "Brandon Turner",
    "category": "Artist",
    "location": "Newcastle",
    "instagram": "@shvndv.uk",
    "instagramUrl": "https://www.instagram.com/shvndv.uk/",
    "websiteUrl": "https://www.depop.com/shvndv",
    "description": "An independent maker creating clothing with original lino-printed designs.",
    "featured": false
  },
  {
    "id": "brittania-douglas",
    "name": "Brittania Douglas",
    "category": "Artist",
    "location": "North Shields",
    "instagram": "@myth_and_moon_relics",
    "instagramUrl": "https://www.instagram.com/myth_and_moon_relics/",
    "websiteUrl": "https://www.etsy.com/shop/MythAndMoonRelics",
    "description": "A jewellery maker celebrating nature and the past through dried botanicals, ethically sourced insects and naturally scavenged bones.",
    "featured": false
  },
  {
    "id": "bruce-parker",
    "name": "Bruce Parker",
    "category": "Artist",
    "location": "Northumberland",
    "instagram": "@brucey.parker",
    "instagramUrl": "https://www.instagram.com/brucey.parker/",
    "websiteUrl": "https://brucey-art.com",
    "description": "An artist based in Northumberland.",
    "featured": false
  },
  {
    "id": "canny-cool-prints",
    "name": "Canny Cool Prints",
    "category": "Artist",
    "location": "Blyth",
    "instagram": "@canny_cool_prints",
    "instagramUrl": "https://www.instagram.com/canny_cool_prints/",
    "websiteUrl": "https://www.cannycoolprints.com/",
    "description": "Helen Richardson creates Canny Cool Prints of familiar places using lino and traditional carving and printing methods.",
    "featured": false
  },
  {
    "id": "catherine-muir",
    "name": "Catherine Muir",
    "category": "Designer",
    "location": "Durham",
    "instagram": "@catherine_a_muir",
    "instagramUrl": "https://www.instagram.com/catherine_a_muir/",
    "websiteUrl": "",
    "description": "A freelance interior designer supporting fellow designers, architects and fitters with their projects.",
    "featured": false
  },
  {
    "id": "charlie-jobling-jones",
    "name": "Charlie Jobling-Jones",
    "category": "Photographer",
    "location": "Sunderland",
    "instagram": "@ajlphotoanddesign",
    "instagramUrl": "https://www.instagram.com/ajlphotoanddesign/",
    "websiteUrl": "",
    "description": "A Sunderland photographer capturing pets, families, couples and live performances, with a growing focus on brand and business work.",
    "featured": false
  },
  {
    "id": "chloe-watson",
    "name": "Chloe Watson",
    "category": "Musician",
    "location": "Gateshead",
    "instagram": "@annie_enclave",
    "instagramUrl": "https://www.instagram.com/annie_enclave/",
    "websiteUrl": "https://youtube.com/@annieenclave",
    "description": "An intimate live music project built around performance, improvisation and playful audience participation.",
    "featured": false
  },
  {
    "id": "chrissy",
    "name": "Chrissy",
    "category": "Creative",
    "location": "Darlington",
    "instagram": "Petitepixie.model",
    "instagramUrl": "https://www.instagram.com/Petitepixie.model/",
    "websiteUrl": "",
    "description": "A creative based in Darlington.",
    "featured": false
  },
  {
    "id": "dale-binney",
    "name": "Dale Binney",
    "category": "Artist",
    "location": "Gateshead",
    "instagram": "@twenty_minus_two",
    "instagramUrl": "https://www.instagram.com/twenty_minus_two/",
    "websiteUrl": "https://www.twentyminustwo.wordpress.com",
    "description": "TwentyMinusTwo is the creative identity of Dale Binney, a multimedia artist based in North East England.",
    "featured": true
  },
  {
    "id": "danielle-cosgrove",
    "name": "Danielle Cosgrove",
    "category": "Photographer",
    "location": "Northumberland",
    "instagram": "@daniicaptures_",
    "instagramUrl": "https://www.instagram.com/daniicaptures_/",
    "websiteUrl": "",
    "description": "A creative with a barbering background whose work brings more male models into focus.",
    "featured": false
  },
  {
    "id": "danielle-stephenson",
    "name": "Danielle Stephenson",
    "category": "Artist",
    "location": "Durham",
    "instagram": "@dels_doodles",
    "instagramUrl": "https://www.instagram.com/dels_doodles/",
    "websiteUrl": "",
    "description": "A full-time artist who left a corporate career to build an independent creative practice.",
    "featured": false
  },
  {
    "id": "david-jackson",
    "name": "David Jackson",
    "category": "Photographer",
    "location": "Newcastle",
    "instagram": "https://www.instagram.com/prettyurban_gallery?igsi=dzB3Mzkyb3RlcHJn&utm_source=qr",
    "instagramUrl": "https://www.instagram.com/prettyurban_gallery/",
    "websiteUrl": "https://prettyurban.shop/",
    "description": "Pretty Urban turns close-cropped photographs of graffiti and abandoned spaces into textured abstract studies of the city.",
    "featured": false
  },
  {
    "id": "deb-cooper",
    "name": "Deb Cooper",
    "category": "Artist",
    "location": "Durham and Northumberland",
    "instagram": "@debcoopertextileart",
    "instagramUrl": "https://www.instagram.com/debcoopertextileart/",
    "websiteUrl": "https://www.debcoopertextileart.com/",
    "description": "A mixed-media textile artist.",
    "featured": false
  },
  {
    "id": "donna",
    "name": "Donna",
    "category": "Artist",
    "location": "Tynemouth",
    "instagram": "@littlegrey_studio",
    "instagramUrl": "https://www.instagram.com/littlegrey_studio/",
    "websiteUrl": "https://littlegrey.bigcartel.com/",
    "description": "An artist painting delicate birds and mice onto carefully sourced antique and vintage paper, giving time-worn pieces a new life.",
    "featured": false
  },
  {
    "id": "ellen-barr",
    "name": "Ellen Barr",
    "category": "Other",
    "location": "Gateshead",
    "instagram": "@ellenbarrcontent",
    "instagramUrl": "https://www.instagram.com/ellenbarrcontent/",
    "websiteUrl": "https://ellenbarrcontent.com",
    "description": "A content writer and strategist from Gateshead.",
    "featured": false
  },
  {
    "id": "ellie-armstrong",
    "name": "Ellie Armstrong",
    "category": "Photographer",
    "location": "Peterlee",
    "instagram": "@ellaminstudiobytheringside",
    "instagramUrl": "https://www.instagram.com/ellaminstudiobytheringside/",
    "websiteUrl": "",
    "description": "A photographer and visual storyteller based in Peterlee.",
    "featured": false
  },
  {
    "id": "ellie-gair",
    "name": "Ellie Gair",
    "category": "Architect",
    "location": "Newcastle",
    "instagram": "@studiomintuk",
    "instagramUrl": "https://www.instagram.com/studiomintuk/",
    "websiteUrl": "https://www.studio-mint.co.uk/",
    "description": "An architect working across Newcastle and the wider North East.",
    "featured": false
  },
  {
    "id": "ellie-grassick",
    "name": "Ellie Grassick",
    "category": "Local business",
    "location": "Newcastle",
    "instagram": "@rindill.makes",
    "instagramUrl": "https://www.instagram.com/rindill.makes/",
    "websiteUrl": "https://www.rindillmakes.co.uk",
    "description": "Rindill Makes creates handmade stainless-steel jewellery inspired by history, nature, fantasy and folklore.",
    "featured": false
  },
  {
    "id": "elliott-mccann",
    "name": "Elliott McCann",
    "category": "Artist",
    "location": "Newcastle",
    "instagram": "@redrocketteart",
    "instagramUrl": "https://www.instagram.com/redrocketteart/",
    "websiteUrl": "https://www.redrockette.com/",
    "description": "An artist and printmaker from Newcastle upon Tyne.",
    "featured": false
  },
  {
    "id": "emily-hline",
    "name": "Emily Hline",
    "category": "Artist",
    "location": "Newcastle Upon Tyne",
    "instagram": "@emilyhlineillo",
    "instagramUrl": "https://www.instagram.com/emilyhlineillo/",
    "websiteUrl": "",
    "description": "A freelance illustrator who returned to Newcastle after studying illustration in Kent.",
    "featured": false
  },
  {
    "id": "emma-bloomfield",
    "name": "Emma Bloomfield",
    "category": "Creative",
    "location": "Sunderland",
    "instagram": "@emmarose_aerial",
    "instagramUrl": "https://www.instagram.com/emmarose_aerial/",
    "websiteUrl": "https://www.bloomaerial.co.uk",
    "description": "An aerial performer and teacher working from AAA Sports in Sunderland since 2009.",
    "featured": false
  },
  {
    "id": "emma-moffat-knox",
    "name": "Emma Moffat-Knox",
    "category": "Local business",
    "location": "North Shields",
    "instagram": "TrickRTreat_barber",
    "instagramUrl": "https://www.instagram.com/TrickRTreat_barber/",
    "websiteUrl": "https://wrongcrowdmerch.com/collections/bad-blood-barbers",
    "description": "An independent business based in North Shields.",
    "featured": false
  },
  {
    "id": "eoin-kavanagh",
    "name": "Eoin Kavanagh",
    "category": "Photographer",
    "location": "Newcastle/Sunderland/Durham",
    "instagram": "@ephotographyncl",
    "instagramUrl": "https://www.instagram.com/ephotographyncl/",
    "websiteUrl": "",
    "description": "A photographer working across Newcastle, Sunderland and Durham.",
    "featured": false
  },
  {
    "id": "faythe-lockwood",
    "name": "Faythe Lockwood",
    "category": "Artist",
    "location": "Gateshead",
    "instagram": "@faythelockwood",
    "instagramUrl": "https://www.instagram.com/faythelockwood/",
    "websiteUrl": "https://cara.app/faithl",
    "description": "A lesbian fantasy artist developing two queer fantasy novels, Fire Angels and Rosa the Earth Elemental.",
    "featured": false
  },
  {
    "id": "finch",
    "name": "Finch",
    "category": "Artist",
    "location": "Horden, County Durham",
    "instagram": "Finchwilkinsart",
    "instagramUrl": "https://www.instagram.com/Finchwilkinsart/",
    "websiteUrl": "https://finchwilkinsart.xyz",
    "description": "An illustration graduate developing an independent art business alongside postgraduate study.",
    "featured": false
  },
  {
    "id": "forbes-finishings",
    "name": "Forbes Finishings",
    "category": "Local business",
    "location": "Whitley Bay",
    "instagram": "@forbesfinishings",
    "instagramUrl": "https://www.instagram.com/forbesfinishings/",
    "websiteUrl": "https://www.forbesfinishings.com",
    "description": "A sustainable gift-wrapping studio running public workshops, brand projects and creative team-building sessions using unexpected reclaimed materials.",
    "featured": false
  },
  {
    "id": "gabrielle-binks",
    "name": "Gabrielle Binks",
    "category": "Creative",
    "location": "Chopwell, Gatesheah",
    "instagram": "gabriellebinksstudio",
    "instagramUrl": "https://www.instagram.com/gabriellebinksstudio/",
    "websiteUrl": "https://www.gabriellebinksstudio.com",
    "description": "An independent maker designing and selling original knitwear.",
    "featured": false
  },
  {
    "id": "gayle-foster",
    "name": "Gayle Foster",
    "category": "Local business",
    "location": "Corbridge, Northumberland",
    "instagram": "@vintageatthetower",
    "instagramUrl": "https://www.instagram.com/vintageatthetower/",
    "websiteUrl": "https://vintageatthetower.com/",
    "description": "A Corbridge vintage shop specialising in carefully selected, one-off accessories.",
    "featured": false
  },
  {
    "id": "glenda-turnbull",
    "name": "Glenda Turnbull",
    "category": "Artist",
    "location": "Northumberland",
    "instagram": "@glendaturnbullart",
    "instagramUrl": "https://www.instagram.com/glendaturnbullart/",
    "websiteUrl": "",
    "description": "Artist based in Northumberland.",
    "featured": false
  },
  {
    "id": "grace-raymond-burrows",
    "name": "Grace Raymond-Burrows",
    "category": "Creative",
    "location": "Newton Aycliffe",
    "instagram": "@that_vegan_vulture",
    "instagramUrl": "https://www.instagram.com/that_vegan_vulture/",
    "websiteUrl": "https://www.thatveganvulture.com",
    "description": "A vegan forager creating respectful decorative work from responsibly gathered animal bones and skulls.",
    "featured": false
  },
  {
    "id": "haydn-brown",
    "name": "Haydn Brown",
    "category": "Photographer",
    "location": "Gateshead",
    "instagram": "@haydnb_photography",
    "instagramUrl": "https://www.instagram.com/haydnb_photography/",
    "websiteUrl": "https://www.haydnbrownphotography.com/",
    "description": "An LGBTQ+ photographer and the creator of Anti Headshots.",
    "featured": false
  },
  {
    "id": "heather-close",
    "name": "Heather Close",
    "category": "Designer",
    "location": "Sunderland",
    "instagram": "@penten_designs",
    "instagramUrl": "https://www.instagram.com/penten_designs/",
    "websiteUrl": "https://www.pentendesigns.com",
    "description": "A freelance graphic and brand designer based in the North East.",
    "featured": false
  },
  {
    "id": "hels",
    "name": "Hels",
    "category": "Artist",
    "location": "Sunderland",
    "instagram": "@renegadepenguin.studio",
    "instagramUrl": "https://www.instagram.com/renegadepenguin.studio/",
    "websiteUrl": "https://www.renegadepenguin.studio",
    "description": "An illustrator and surface-pattern designer available for licensing and commissioned work.",
    "featured": false
  },
  {
    "id": "imogen-andrews",
    "name": "Imogen Andrews",
    "category": "Artist",
    "location": "Newcastle",
    "instagram": "@i_violetart",
    "instagramUrl": "https://www.instagram.com/i_violetart/",
    "websiteUrl": "",
    "description": "A collage artist developing an original card project inspired by Pokémon and years of personal practice.",
    "featured": false
  },
  {
    "id": "jack-alberts---trigo-studio",
    "name": "Jack Alberts / Trigo Studio",
    "category": "Creative",
    "location": "Newcastle",
    "instagram": "@trigo.studio",
    "instagramUrl": "https://www.instagram.com/trigo.studio/",
    "websiteUrl": "https://www.trigodesign.com",
    "description": "Trigo Studio is a full-stack creative agency based in Newcastle upon Tyne, specialising in branding, websites, content and digital design.",
    "featured": false
  },
  {
    "id": "jack-holden",
    "name": "Jack Holden",
    "category": "3D Animation",
    "location": "Newcastle",
    "instagram": "@cgicentralncl",
    "instagramUrl": "https://www.instagram.com/cgicentralncl/",
    "websiteUrl": "https://www.jackdotfbx.co.uk",
    "description": "A freelance 3D artist and animator, and one half of CGI Central NCL.",
    "featured": false
  },
  {
    "id": "james-robinson",
    "name": "James Robinson",
    "category": "Photographer",
    "location": "Newcastle",
    "instagram": "@shotbyjsr",
    "instagramUrl": "https://www.instagram.com/shotbyjsr/",
    "websiteUrl": "https://jsrphotos.co.uk",
    "description": "A North East photo and video creative available for projects further afield.",
    "featured": false
  },
  {
    "id": "jamie-lee-harrison",
    "name": "Jamie Lee Harrison",
    "category": "Musician",
    "location": "Newcastle",
    "instagram": "@JamieLHarrison",
    "instagramUrl": "https://www.instagram.com/JamieLHarrison/",
    "websiteUrl": "https://www.jamieleeharrison.com",
    "description": "A Gateshead-born musician with a strong connection to the region and its creative community.",
    "featured": false
  },
  {
    "id": "jemma-marsh",
    "name": "Jemma Marsh",
    "category": "Artist",
    "location": "Newcastle",
    "instagram": "Lahuevo.arte",
    "instagramUrl": "https://www.instagram.com/Lahuevo.arte/",
    "websiteUrl": "",
    "description": "A painter and maker whose practice moves across several creative forms.",
    "featured": false
  },
  {
    "id": "jennifer-parkins",
    "name": "Jennifer Parkins",
    "category": "Creative",
    "location": "Gateshead",
    "instagram": "@the.valley.garden",
    "instagramUrl": "https://www.instagram.com/the.valley.garden/",
    "websiteUrl": "",
    "description": "A gardening creator sharing honest lessons, practical tips and inspiration for north-facing gardens in the North East.",
    "featured": false
  },
  {
    "id": "jessica-penrose",
    "name": "Jessica Penrose",
    "category": "Local business",
    "location": "Newcastle upon Tyne",
    "instagram": "@thefindouseburn",
    "instagramUrl": "https://www.instagram.com/thefindouseburn/",
    "websiteUrl": "https://www.thefindouseburn.com",
    "description": "The curator of a bricks-and-mortar shop filled with work from local artists, makers and independent sellers.",
    "featured": false
  },
  {
    "id": "jessie-gaffney",
    "name": "Jessie Gaffney",
    "category": "Photographer",
    "location": "Newcastle",
    "instagram": "@crispsandwichstudio",
    "instagramUrl": "https://www.instagram.com/crispsandwichstudio/",
    "websiteUrl": "https://www.crispsandwichstudio.com",
    "description": "Crisp Sandwich Studio is Jessie Gaffney’s Newcastle photography and stop-motion studio, working with local businesses and musicians.",
    "featured": false
  },
  {
    "id": "jill-lewis",
    "name": "Jill Lewis",
    "category": "Calligraphy engraving",
    "location": "County Durham",
    "instagram": "Lewisengraving",
    "instagramUrl": "https://www.instagram.com/Lewisengraving/",
    "websiteUrl": "https://www.lewis-engraving.com",
    "description": "A calligrapher who hand-engraves lasting personal details onto meaningful objects.",
    "featured": false
  },
  {
    "id": "jo-lamoureux",
    "name": "Jo Lamoureux",
    "category": "Artist",
    "location": "South Tyneside",
    "instagram": "Jolamoureux.ceramics",
    "instagramUrl": "https://www.instagram.com/Jolamoureux.ceramics/",
    "websiteUrl": "https://www.jolamoureux.co.uk",
    "description": "Working mainly with hand-built clay, Jo explores forms that sit somewhere between plants, sea life and imagined organisms.",
    "featured": false
  },
  {
    "id": "joanna-long",
    "name": "Joanna Long",
    "category": "Journalist / reviewer / storyteller",
    "location": "Barnard Castle County Durha",
    "instagram": "@echoes_in_ink_2025",
    "instagramUrl": "https://www.instagram.com/echoes_in_ink_2025/",
    "websiteUrl": "",
    "description": "A journalist, reviewer and storyteller based in Barnard Castle, County Durham.",
    "featured": false
  },
  {
    "id": "joanne-lowes",
    "name": "Joanne Lowes",
    "category": "Local business",
    "location": "Newcastle",
    "instagram": "@matchaevents",
    "instagramUrl": "https://www.instagram.com/matchaevents/",
    "websiteUrl": "https://www.matchaevents.co.uk",
    "description": "A former maker who now runs events that champion independent creatives and give first-time stallholders a place to start.",
    "featured": false
  },
  {
    "id": "jody-irving",
    "name": "Jody Irving",
    "category": "Musician",
    "location": "Newcastle",
    "instagram": "@jodybigfoot",
    "instagramUrl": "https://www.instagram.com/jodybigfoot/",
    "websiteUrl": "https://www.youtube.com/trinitylofi",
    "description": "A rapper making albums in niche genres and pushing at their boundaries.",
    "featured": false
  },
  {
    "id": "joe-wilson-nami-creative",
    "name": "Joe Wilson / NAMI Creative",
    "category": "Creative consultant",
    "location": "Newcastle upon Tyne",
    "instagram": "@namicreativeuk",
    "instagramUrl": "https://www.instagram.com/namicreativeuk/",
    "websiteUrl": "https://namicreative.co.uk/",
    "description": "A freelance creative consultant helping North East creatives, brands and businesses make waves, get their work seen and create a stronger impact.",
    "profileImage": "/images/network/members/joe-wilson-nami-creative.webp",
    "imageAlt": "Joe Wilson of NAMI Creative",
    "featured": false
  },
  {
    "id": "jolene-lowe",
    "name": "Jolene Lowe",
    "category": "Artist",
    "location": "North Shields",
    "instagram": "Ikiart963",
    "instagramUrl": "https://www.instagram.com/Ikiart963/",
    "websiteUrl": "",
    "description": "An artist creating wall art and smaller pieces from clay, handmade paper and broken pottery.",
    "featured": false
  },
  {
    "id": "jonas-kontautas",
    "name": "Jonas Kontautas",
    "category": "Photographer",
    "location": "South Shields",
    "instagram": "ByJonasFilms",
    "instagramUrl": "https://www.instagram.com/ByJonasFilms/",
    "websiteUrl": "https://jonaskonta.com",
    "description": "A videographer working across esports, business projects and weddings.",
    "featured": false
  },
  {
    "id": "joseph-marsh",
    "name": "Joseph Marsh",
    "category": "Artist",
    "location": "Newcastle",
    "instagram": "@jpmarsh_illustration",
    "instagramUrl": "https://www.instagram.com/jpmarsh_illustration/",
    "websiteUrl": "https://www.jpmarshillustration.com/",
    "description": "An artist creating original paintings, art prints and homeware.",
    "featured": false
  },
  {
    "id": "kae-beth",
    "name": "Kae Beth",
    "category": "Creative",
    "location": "Gateshead",
    "instagram": "Kae.fxcking.beth",
    "instagramUrl": "https://www.instagram.com/Kae.fxcking.beth/",
    "websiteUrl": "",
    "description": "A creator exploring fetish and alternative lifestyles as an open and valid form of creative practice.",
    "featured": false
  },
  {
    "id": "karen-ruffles",
    "name": "Karen Ruffles",
    "category": "Artist",
    "location": "Byker, Newcastle upon Tyne",
    "instagram": "@drawingindark",
    "instagramUrl": "https://www.instagram.com/drawingindark/",
    "websiteUrl": "https://www.drawingindark.co.uk/",
    "description": "A Byker-based visual artist specialising in charcoal landscapes, wildlife and gothic illustration.",
    "featured": false
  },
  {
    "id": "kate-anderson",
    "name": "Kate Anderson",
    "category": "Artist",
    "location": "Newcastle",
    "instagram": "kate_anderson_artist",
    "instagramUrl": "https://www.instagram.com/kate_anderson_artist/",
    "websiteUrl": "",
    "description": "A Geordie painter creating work that shifts between surreal, creepy, cute and sinister.",
    "featured": false
  },
  {
    "id": "kate-miller",
    "name": "Kate Miller",
    "category": "Artist",
    "location": "Newcastle",
    "instagram": "@bykatemillerprints",
    "instagramUrl": "https://www.instagram.com/bykatemillerprints/",
    "websiteUrl": "https://bykatemiller.com",
    "description": "A printmaker creating limited-edition linocuts inspired by the landscapes and nature of the North East.",
    "featured": false
  },
  {
    "id": "katie-dyer",
    "name": "Katie Dyer",
    "category": "Designer",
    "location": "Stockton on Tees",
    "instagram": "katiedyerdesign",
    "instagramUrl": "https://www.instagram.com/katiedyerdesign/",
    "websiteUrl": "https://www.katiedyerdesign.co.uk",
    "description": "A North East print designer building every design from original hand-painted illustrations.",
    "featured": false
  },
  {
    "id": "katie-rzedzian",
    "name": "Katie Rzedzian",
    "category": "Artist",
    "location": "North Tyneside",
    "instagram": "@katierzedzianart",
    "instagramUrl": "https://www.instagram.com/katierzedzianart/",
    "websiteUrl": "https://folksy.com/shops/katierzedzianart",
    "description": "A self-taught Whitley Bay artist creating landscapes and seascapes shaped by a love of the outdoors.",
    "featured": false
  },
  {
    "id": "kelly-morgan",
    "name": "Kelly Morgan",
    "category": "Artist",
    "location": "Ouseburn,Newcastle",
    "instagram": "@kellymorgan.artist",
    "instagramUrl": "https://www.instagram.com/kellymorgan.artist/",
    "websiteUrl": "https://kellymorgan.co.uk/",
    "description": "A glass painter making work full of colour, character and life.",
    "featured": false
  },
  {
    "id": "kelly-smith",
    "name": "Kelly Smith",
    "category": "Designer",
    "location": "Durham",
    "instagram": "@spelkstudio",
    "instagramUrl": "https://www.instagram.com/spelkstudio/",
    "websiteUrl": "https://www.spelk.studio",
    "description": "An interiors studio specialising in kitchens and furniture.",
    "featured": false
  },
  {
    "id": "kim-mcdermottroe",
    "name": "Kim McDermottroe",
    "category": "Artist",
    "location": "Teesside",
    "instagram": "@greenerlavelle",
    "instagramUrl": "https://www.instagram.com/greenerlavelle/",
    "websiteUrl": "https://www.greenerlavelle.co.uk",
    "description": "An artist based in Teesside.",
    "featured": false
  },
  {
    "id": "larissa-padgett",
    "name": "Larissa Padgett",
    "category": "Artist",
    "location": "Sunderland",
    "instagram": "@larissapadgettart",
    "instagramUrl": "https://www.instagram.com/larissapadgettart/",
    "websiteUrl": "",
    "description": "A Sunderland-based artist creating large-scale mixed-media portraits.",
    "featured": false
  },
  {
    "id": "laura-black",
    "name": "Laura Black",
    "category": "Artist",
    "location": "South Shields",
    "instagram": "Laura_black_tattoo",
    "instagramUrl": "https://www.instagram.com/Laura_black_tattoo/",
    "websiteUrl": "",
    "description": "A tattoo artist and the founder of Dead Happy Tattoo, an independent studio with creativity beyond the chair.",
    "featured": false
  },
  {
    "id": "laura-crow",
    "name": "Laura Crow",
    "category": "Designer",
    "location": "Gateshead",
    "instagram": "@thecrowfactory",
    "instagramUrl": "https://www.instagram.com/thecrowfactory/",
    "websiteUrl": "",
    "description": "A designer and illustrator drawn to brutalist buildings, North East places and especially where the two meet.",
    "featured": false
  },
  {
    "id": "laura-miller",
    "name": "Laura Miller",
    "category": "Artist",
    "location": "Gateshead",
    "instagram": "@nerd_that_draws",
    "instagramUrl": "https://www.instagram.com/nerd_that_draws/",
    "websiteUrl": "https://www.nerdthatdraws.com",
    "description": "An artist based in Gateshead.",
    "featured": false
  },
  {
    "id": "laura-moore",
    "name": "Laura Moore",
    "category": "Artist",
    "location": "Newcastle/Tynemouth",
    "instagram": "@lauramooreartist",
    "instagramUrl": "https://www.instagram.com/lauramooreartist/",
    "websiteUrl": "https://www.lauramoore.art",
    "description": "An emerging illustrator building a new portfolio and preparing to launch an independent print shop.",
    "featured": false
  },
  {
    "id": "laura-rosierse",
    "name": "Laura Rosierse",
    "category": "Creative",
    "location": "Newcastle Upon Tyne",
    "instagram": "llivelymusic",
    "instagramUrl": "https://www.instagram.com/llivelymusic/",
    "websiteUrl": "https://llivelymusic.com/",
    "description": "LLIVELY Music is an independent music PR, promotion and artist-advice company built around honesty, openness and affordability.",
    "featured": false
  },
  {
    "id": "lauren-shakespeare",
    "name": "Lauren Shakespeare",
    "category": "Artist",
    "location": "Newcastle",
    "instagram": "@L.shakespeare.art",
    "instagramUrl": "https://www.instagram.com/L.shakespeare.art/",
    "websiteUrl": "",
    "description": "An oil painter documenting Newcastle’s alternative scene through figurative work.",
    "featured": false
  },
  {
    "id": "leona-armstrong",
    "name": "Leona Armstrong",
    "category": "Creative",
    "location": "Gateshead",
    "instagram": "@feral_metale",
    "instagramUrl": "https://www.instagram.com/feral_metale/",
    "websiteUrl": "",
    "description": "A queer, non-binary transfeminine artist, model and photographer focused on alternative subculture and fashion.",
    "featured": false
  },
  {
    "id": "lewis",
    "name": "Lewis",
    "category": "Creative",
    "location": "Newcastle Upon Tyne, United Kingdom",
    "instagram": "@the_filmsquid",
    "instagramUrl": "https://www.instagram.com/the_filmsquid/",
    "websiteUrl": "",
    "description": "A film and television production graduate specialising in screenwriting.",
    "featured": false
  },
  {
    "id": "lewis-dimmick",
    "name": "Lewis Dimmick",
    "category": "Artist",
    "location": "Whitley Bay",
    "instagram": "@ld.fineart",
    "instagramUrl": "https://www.instagram.com/ld.fineart/",
    "websiteUrl": "https://ldfineart.com",
    "description": "An oil painter working from life, with experience across gallery exhibitions and projects for North East festivals and organisations.",
    "featured": false
  },
  {
    "id": "lewis-paul-farrow",
    "name": "Lewis Paul Farrow",
    "category": "Designer",
    "location": "Durham",
    "instagram": "@graphicdesignbylewis",
    "instagramUrl": "https://www.instagram.com/graphicdesignbylewis/",
    "websiteUrl": "https://lewisfarrowdesign479.myportfolio.com/work",
    "description": "A creative director with two decades of experience building brands, campaigns and identities across combat sports, football and performance-led organisations.",
    "featured": false
  },
  {
    "id": "liv-askwith",
    "name": "Liv Askwith",
    "category": "Artist",
    "location": "Hartlepool",
    "instagram": "@Liv_Askwith_Art",
    "instagramUrl": "https://www.instagram.com/Liv_Askwith_Art/",
    "websiteUrl": "",
    "description": "A painter exploring her experience as a queer woman and creating work intended to help others feel seen.",
    "featured": false
  },
  {
    "id": "maeve-winters",
    "name": "Maeve Winters",
    "category": "Creative",
    "location": "Gateshead",
    "instagram": "@maevewinters_altmodel",
    "instagramUrl": "https://www.instagram.com/maevewinters_altmodel/",
    "websiteUrl": "https://purpleport.com/portfolio/maevewinter/",
    "description": "An alternative model and actress drawn to unconventional aesthetics, expressive characters and creative collaboration.",
    "featured": false
  },
  {
    "id": "mark-folland",
    "name": "Mark Folland",
    "category": "Recording / mixing Studio & post production",
    "location": "Hartlepool",
    "instagram": "@follrecordingandproduction",
    "instagramUrl": "https://www.instagram.com/follrecordingandproduction/",
    "websiteUrl": "https://www.follrecordingandproduction.co.uk/",
    "description": "A recording and mixing engineer working with bands across genres, experience levels and budgets.",
    "featured": false
  },
  {
    "id": "mark-ingram",
    "name": "Mark Ingram",
    "category": "Artist",
    "location": "Newcastle",
    "instagram": "@markoingram_art",
    "instagramUrl": "https://www.instagram.com/markoingram_art/",
    "websiteUrl": "",
    "description": "A classical oil painter using the visual language of historic painting to explore queer identity and alternative communities.",
    "featured": false
  },
  {
    "id": "maxine-fell---northern-dance",
    "name": "Maxine Fell / Northern Dance",
    "category": "Professional dance company.",
    "location": "Newcastle",
    "instagram": "@northerndance_28b. @maxinefell_28b",
    "instagramUrl": "https://www.instagram.com/northerndance_28b./",
    "websiteUrl": "https://www.northerndance.org.uk",
    "description": "The artistic director, dancer and choreographer behind Northern Dance.",
    "featured": false
  },
  {
    "id": "melanie-heaps",
    "name": "Melanie Heaps",
    "category": "Creative",
    "location": "Choppington Northumberland",
    "instagram": "@leggy_bird_creative",
    "instagramUrl": "https://www.instagram.com/leggy_bird_creative/",
    "websiteUrl": "https://www.leggybirdcreative.com",
    "description": "Leggy Bird Creative makes neuroaffirming art, including long-legged bird sculptures formed from brightly coloured rolled paper.",
    "featured": false
  },
  {
    "id": "melissa-duncan",
    "name": "Melissa Duncan",
    "category": "Artist",
    "location": "Sunderland",
    "instagram": "@melissaduncan.art",
    "instagramUrl": "https://www.instagram.com/melissaduncan.art/",
    "websiteUrl": "",
    "description": "A contemporary artist using expanded painting to explore the move from childhood into adulthood and the search for play.",
    "featured": false
  },
  {
    "id": "michael-clark",
    "name": "Michael Clark",
    "category": "Local business",
    "location": "Gateshead/North Shields",
    "instagram": "@evil_band_merch",
    "instagramUrl": "https://www.instagram.com/evil_band_merch/",
    "websiteUrl": "https://evilbandmerch.com",
    "description": "An independent screen printer producing organic and retail garments for bands, tattoo artists, creators and pubs.",
    "featured": false
  },
  {
    "id": "mike",
    "name": "Mike",
    "category": "Designer",
    "location": "Newcastle",
    "instagram": "@fettlerdesign",
    "instagramUrl": "https://www.instagram.com/fettlerdesign/",
    "websiteUrl": "https://www.fettler.co.uk",
    "description": "A designer based in Newcastle.",
    "featured": false
  },
  {
    "id": "miriam-yaya",
    "name": "Miriam Yaya",
    "category": "Creative",
    "location": "Newcastle",
    "instagram": "miriam.co.uk",
    "instagramUrl": "https://www.instagram.com/miriam.co.uk/",
    "websiteUrl": "",
    "description": "A creative based in Newcastle.",
    "featured": false
  },
  {
    "id": "natasha-armstrong",
    "name": "Natasha Armstrong",
    "category": "Artist",
    "location": "Durham/Sunderland/Newcastle",
    "instagram": "@natasha.armstrongart",
    "instagramUrl": "https://www.instagram.com/natasha.armstrongart/",
    "websiteUrl": "",
    "description": "An artist working across Durham, Sunderland and Newcastle.",
    "featured": false
  },
  {
    "id": "neil-johnson",
    "name": "Neil Johnson",
    "category": "Photographer",
    "location": "Chester-le-Street",
    "instagram": "@mediaratz",
    "instagramUrl": "https://www.instagram.com/mediaratz/",
    "websiteUrl": "https://mediaratz.com",
    "description": "A creative portrait photographer using smoke, projection, lasers, UV light, fire and underwater techniques.",
    "featured": false
  },
  {
    "id": "nicholle",
    "name": "Nicholle",
    "category": "Content creator",
    "location": "h",
    "instagram": "@na.creativestudio",
    "instagramUrl": "https://www.instagram.com/na.creativestudio/",
    "websiteUrl": "",
    "description": "A content and social media studio helping local businesses turn everyday work into clear, human content that builds trust and enquiries.",
    "featured": false
  },
  {
    "id": "nicola-hunter",
    "name": "Nicola Hunter",
    "category": "Photographer",
    "location": "Newcastle",
    "instagram": "nicolajay.photos",
    "instagramUrl": "https://www.instagram.com/nicolajay.photos/",
    "websiteUrl": "https://www.nicolajayphotos.com",
    "description": "A wedding photographer capturing celebrations filled with fun, warmth and affection.",
    "featured": false
  },
  {
    "id": "nicola-irwin",
    "name": "Nicola Irwin",
    "category": "Artist",
    "location": "Gateshead",
    "instagram": "@betsy_and_beanz_designs",
    "instagramUrl": "https://www.instagram.com/betsy_and_beanz_designs/",
    "websiteUrl": "https://www.betsyandbeanz.co.uk",
    "description": "An artist creating detailed pet portraits in pastel.",
    "featured": false
  },
  {
    "id": "nicola-jane-hall",
    "name": "Nicola Jane Hall",
    "category": "Designer",
    "location": "North Shields",
    "instagram": "@AngelicVision007",
    "instagramUrl": "https://www.instagram.com/AngelicVision007/",
    "websiteUrl": "",
    "description": "A multidisciplinary artist and designer currently working with repurposed and hard-to-recycle textiles.",
    "featured": false
  },
  {
    "id": "nicole-pook",
    "name": "Nicole Pook",
    "category": "Artist",
    "location": "Middlesbrough",
    "instagram": "Higherself_rituals",
    "instagramUrl": "https://www.instagram.com/Higherself_rituals/",
    "websiteUrl": "",
    "description": "A multidisciplinary maker creating theatrical masks and props, jewellery, wire-wrapped crystals, papier-mâché and clay pieces.",
    "featured": false
  },
  {
    "id": "northern-display-painters-guild",
    "name": "Northern Display Painters Guild",
    "category": "Miniature and figure display painting group",
    "location": "Newcastle",
    "instagram": "@NORTHERNDPG",
    "instagramUrl": "https://www.instagram.com/NORTHERNDPG/",
    "websiteUrl": "http://northerndpg.co.uk/",
    "description": "A friendly group for miniature, figure and bust painters to meet, share knowledge and develop their skills together.",
    "featured": false
  },
  {
    "id": "paul-wright",
    "name": "Paul Wright",
    "category": "Artist",
    "location": "Newcastle",
    "instagram": "@tyneratcreations",
    "instagramUrl": "https://www.instagram.com/tyneratcreations/",
    "websiteUrl": "https://tynerat.com",
    "description": "An artist building tiny scenes inside spray cans and other unexpected objects.",
    "featured": false
  },
  {
    "id": "phil-davison-nice-face-apparel",
    "name": "Phil Davison (Nice Face Apparel)",
    "category": "Local business",
    "location": "Durham",
    "instagram": "@nicefaceappareluk",
    "instagramUrl": "https://www.instagram.com/nicefaceappareluk/",
    "websiteUrl": "https://nicefaceapparel.co.uk/",
    "description": "Nice Face Apparel is an independent clothing brand shaped by tattoo art and culture.",
    "featured": false
  },
  {
    "id": "pointy-features-dan",
    "name": "Pointy Features (Dan)",
    "category": "Musician",
    "location": "Durham",
    "instagram": "@pointyfeatures",
    "instagramUrl": "https://www.instagram.com/pointyfeatures/",
    "websiteUrl": "https://danleakguitar.co.uk",
    "description": "A rock musician creating locally rooted work, including the album River Knows and a song inspired by the Lambton Worm.",
    "featured": false
  },
  {
    "id": "rach",
    "name": "Rach",
    "category": "Local business",
    "location": "Durham",
    "instagram": "@rachdoesmagic",
    "instagramUrl": "https://www.instagram.com/rachdoesmagic/",
    "websiteUrl": "https://www.rachdoesmagic.com",
    "description": "A creative practitioner helping ADHDers and other misfits find space to understand and express themselves.",
    "featured": false
  },
  {
    "id": "rachel-blackwell",
    "name": "Rachel Blackwell",
    "category": "Artist",
    "location": "Newcastle",
    "instagram": "rachelblackwell__",
    "instagramUrl": "https://www.instagram.com/rachelblackwell__/",
    "websiteUrl": "https://www.rachelblackwell.squarespace.com",
    "description": "Artist based in Newcastle.",
    "featured": false
  },
  {
    "id": "ralph-deloso",
    "name": "Ralph Deloso",
    "category": "Photographer",
    "location": "Newcastle",
    "instagram": "@ralph.deloso",
    "instagramUrl": "https://www.instagram.com/ralph.deloso/",
    "websiteUrl": "",
    "description": "Photographer based in Newcastle.",
    "featured": false
  },
  {
    "id": "rebecca-ridley",
    "name": "Rebecca Ridley",
    "category": "Local business",
    "location": "Newcastle & Northumberland",
    "instagram": "@made.upnorth",
    "instagramUrl": "https://www.instagram.com/made.upnorth/",
    "websiteUrl": "",
    "description": "An organiser running creative markets across Newcastle and Northumberland to give local makers, artists and independent businesses a platform.",
    "featured": false
  },
  {
    "id": "reuven-fletcher",
    "name": "Reuven Fletcher",
    "category": "Brand",
    "location": "Newcastle upon Tyne",
    "instagram": "@thesockcouncil",
    "instagramUrl": "https://www.instagram.com/thesockcouncil/",
    "websiteUrl": "https://sockcouncil.com",
    "description": "An independent brand based in Newcastle upon Tyne.",
    "featured": false
  },
  {
    "id": "richard",
    "name": "Richard",
    "category": "Creative",
    "location": "Newcastle upon Tyne",
    "instagram": "Lazerray",
    "instagramUrl": "https://www.instagram.com/Lazerray/",
    "websiteUrl": "https://lazerray.com/",
    "description": "An animator creating motion graphics for businesses and visual-art installations.",
    "featured": false
  },
  {
    "id": "robert",
    "name": "Robert",
    "category": "Creative",
    "location": "Newcastle upon Tyne",
    "instagram": "rfh_creative",
    "instagramUrl": "https://www.instagram.com/rfh_creative/",
    "websiteUrl": "",
    "description": "A creative behind C.A.T.S., a completed limited-run project comprising 233 pieces.",
    "featured": false
  },
  {
    "id": "robrez",
    "name": "RobRez",
    "category": "Artist",
    "location": "Newcastle",
    "instagram": "RobRezzz",
    "instagramUrl": "https://www.instagram.com/RobRezzz/",
    "websiteUrl": "https://robrezart.com",
    "description": "A painter capturing the urban life and pop culture around him.",
    "featured": false
  },
  {
    "id": "rolo",
    "name": "Rolo",
    "category": "Designer",
    "location": "Gateshead",
    "instagram": "@studiodariolina",
    "instagramUrl": "https://www.instagram.com/studiodariolina/",
    "websiteUrl": "https://www.studiodariolina.com",
    "description": "A former teacher and Geordie Italian designer creating bright, bold and colourful work alongside family caring roles.",
    "featured": false
  },
  {
    "id": "sally-anderson-sally-anderson",
    "name": "Sally Anderson",
    "category": "Artist",
    "location": "Sunderland",
    "instagram": "@sallylovessharpies",
    "instagramUrl": "https://www.instagram.com/sallylovessharpies/",
    "websiteUrl": "https://sallyandersonart.com",
    "description": "Artist based in Sunderland.",
    "featured": false
  },
  {
    "id": "sam-aylard",
    "name": "Sam Aylard",
    "category": "Designer",
    "location": "Leeds",
    "instagram": "@aylard.studio",
    "instagramUrl": "https://www.instagram.com/aylard.studio/",
    "websiteUrl": "https://aylard.studio/",
    "description": "A Leeds-based brand and graphic designer creating bold, thoughtful identities grounded in the people behind them.",
    "featured": false
  },
  {
    "id": "sarah-carlton-designbykinship",
    "name": "Sarah Carlton / Design by Kinship",
    "category": "Designer",
    "location": "Durham",
    "instagram": "@designbykinship",
    "instagramUrl": "https://www.instagram.com/designbykinship/",
    "websiteUrl": "https://www.designbykinship.co.uk/",
    "description": "A Durham-based designer working through independent studio Design by Kinship.",
    "featured": false
  },
  {
    "id": "sarah-carlton-billynomates-cowork",
    "name": "Sarah Carlton / Billy No Mates",
    "category": "Community",
    "location": "North East",
    "instagram": "@billynomates_cowork",
    "instagramUrl": "https://www.instagram.com/billynomates_cowork/",
    "websiteUrl": "https://www.billynomatescollective.com/",
    "description": "Billy No Mates is an informal coworking collective bringing freelancers and remote workers together.",
    "featured": false
  },
  {
    "id": "sarah-pavlou",
    "name": "Sarah Pavlou",
    "category": "Artist",
    "location": "Sunderland",
    "instagram": "@sarahpavlou_art",
    "instagramUrl": "https://www.instagram.com/sarahpavlou_art/",
    "websiteUrl": "https://www.sarahpavlouart.com",
    "description": "An abstract artist whose practice draws on a former fashion-design career, years spent living in Cyprus and a life shaped by travel and change.",
    "featured": false
  },
  {
    "id": "sarah-lee-bailey",
    "name": "Sarah-Lee Bailey",
    "category": "Artist",
    "location": "Durham",
    "instagram": "SARAHHYPHENLEE",
    "instagramUrl": "https://www.instagram.com/SARAHHYPHENLEE/",
    "websiteUrl": "",
    "description": "Artist based in Durham.",
    "featured": false
  },
  {
    "id": "sean-hunter-edgar",
    "name": "Sean Hunter-Edgar",
    "category": "Designer",
    "location": "Newcastle",
    "instagram": "@sean.h.edgar",
    "instagramUrl": "https://www.instagram.com/sean.h.edgar/",
    "websiteUrl": "https://www.sean-edgar.com",
    "description": "A senior designer specialising in brand and packaging work for craft beer and fast-moving consumer goods.",
    "featured": false
  },
  {
    "id": "seher-sadiq",
    "name": "Seher Sadiq",
    "category": "Artist",
    "location": "Newcastle",
    "instagram": "@seri_studios",
    "instagramUrl": "https://www.instagram.com/seri_studios/",
    "websiteUrl": "https://www.seristudios.co.uk/",
    "description": "Artist based in Newcastle.",
    "featured": false
  },
  {
    "id": "sophie-stewart",
    "name": "Sophie Stewart",
    "category": "Artist",
    "location": "gateshead/newcastle",
    "instagram": "@doodlesbysophie_",
    "instagramUrl": "https://www.instagram.com/doodlesbysophie_/",
    "websiteUrl": "",
    "description": "An artist making pop-art prints and collages.",
    "featured": false
  },
  {
    "id": "southpaw-company",
    "name": "Southpaw Company",
    "category": "Dance Theatre & Digital Innovation",
    "location": "Sunderland",
    "instagram": "@southpawcompany",
    "instagramUrl": "https://www.instagram.com/southpawcompany/",
    "websiteUrl": "https://southpaw.org.uk",
    "description": "A Sunderland company working across dance theatre and digital innovation.",
    "featured": false
  },
  {
    "id": "sserrated",
    "name": "SSERRATED",
    "category": "Photographer",
    "location": "Newcastle",
    "instagram": "@sserrated",
    "instagramUrl": "https://www.instagram.com/sserrated/",
    "websiteUrl": "https://sserrated.co.uk",
    "description": "A photographer and visual artist whose long-running anonymous community project brings film photography and visual art together.",
    "featured": false
  },
  {
    "id": "stase-jenny",
    "name": "Stase Jenny",
    "category": "Artist",
    "location": "Newcastle, Gateshead",
    "instagram": "Drawingsbystase",
    "instagramUrl": "https://www.instagram.com/Drawingsbystase/",
    "websiteUrl": "",
    "description": "An artist bringing Thai and Scottish influences together within her creative practice.",
    "featured": false
  },
  {
    "id": "steve-lyon-bowes",
    "name": "Steve Lyon-Bowes",
    "category": "Artist",
    "location": "Gateshead",
    "instagram": "@steviebobslb",
    "instagramUrl": "https://www.instagram.com/steviebobslb/",
    "websiteUrl": "",
    "description": "Artist and teacher working in the North East.",
    "featured": false
  },
  {
    "id": "steven-wilson",
    "name": "Steven Wilson",
    "category": "Photographer",
    "location": "Newcastle upon Tyne",
    "instagram": "steven_w_ncl",
    "instagramUrl": "https://www.instagram.com/steven_w_ncl/",
    "websiteUrl": "https://stevenwilsonsw6.wixstudio.com/saintphotography/blank-2-1-2-1-3-1-2-1-1",
    "description": "Photographer based in Newcastle upon Tyne.",
    "featured": false
  },
  {
    "id": "strike-promotions",
    "name": "Strike Promotions",
    "category": "Local business",
    "location": "Newcastle/gateshead",
    "instagram": "@strikepromotionsuk",
    "instagramUrl": "https://www.instagram.com/strikepromotionsuk/",
    "websiteUrl": "https://strikepromotionsne.uk",
    "description": "A small music promoter keeping gigs affordable while connecting local bands with artists from around the country.",
    "featured": false
  },
  {
    "id": "su-devine",
    "name": "Su Devine",
    "category": "Local business",
    "location": "Sunderland",
    "instagram": "Artcafe_sunderland",
    "instagramUrl": "https://www.instagram.com/Artcafe_sunderland/",
    "websiteUrl": "",
    "description": "A community-interest coffee shop with a dedicated workshop space for local artists and creatives to use.",
    "featured": false
  },
  {
    "id": "sue-reed",
    "name": "Sue Reed",
    "category": "Creative",
    "location": "Hexham, Northumberland",
    "instagram": "@suereedwrites",
    "instagramUrl": "https://www.instagram.com/suereedwrites/",
    "websiteUrl": "https://suereedwrites.co.uk",
    "description": "A freelance writer and author exploring environmental issues, respect for nature, individuality and the strength of community.",
    "featured": false
  },
  {
    "id": "sue-ridley-art",
    "name": "Sue Ridley Art",
    "category": "Artist",
    "location": "B.Box Studios, Shieldfield, Newcastle, upon Tyne.",
    "instagram": "@sueridleyart",
    "instagramUrl": "https://www.instagram.com/sueridleyart/",
    "websiteUrl": "",
    "description": "A local artist inspired by the North East and Northumberland coastlines.",
    "featured": false
  },
  {
    "id": "suzie-smith",
    "name": "Suzie Smith",
    "category": "Artist",
    "location": "Sunderland / South Shields",
    "instagram": "@suziesmithdesigns",
    "instagramUrl": "https://www.instagram.com/suziesmithdesigns/",
    "websiteUrl": "https://www.suziesmithdesign.co.uk",
    "description": "A glass artist and MA student based at the National Glass Centre.",
    "featured": false
  },
  {
    "id": "thorn-woods",
    "name": "Thorn Woods",
    "category": "Creative",
    "location": "Newcastle",
    "instagram": "@thorn_faustus @venom_promotions",
    "instagramUrl": "https://www.instagram.com/thorn_faustus/",
    "websiteUrl": "",
    "description": "A fire, burlesque and LED performer who also organises live events.",
    "featured": false
  },
  {
    "id": "twisted-figments",
    "name": "Twisted Figments",
    "category": "Artist",
    "location": "Lincolnshire",
    "instagram": "@twistedfigments",
    "instagramUrl": "https://www.instagram.com/twistedfigments/",
    "websiteUrl": "https://www.instagram.com/twistedfigments",
    "description": "A professional pixel artist designing a video game shaped by horror, 1980s and 1990s culture and nostalgia.",
    "featured": false
  },
  {
    "id": "tyger-comms",
    "name": "Tyger Comms",
    "category": "Local business",
    "location": "Newcastle",
    "instagram": "@tyger.comms",
    "instagramUrl": "https://www.instagram.com/tyger.comms/",
    "websiteUrl": "https://www.tygercomms.co.uk",
    "description": "Founded by PR professional, writer and former digital news editor Jane Imrie, Tyger Comms works with brave, honest and meaningful ideas.",
    "featured": false
  },
  {
    "id": "varie-freyne",
    "name": "Varie Freyne",
    "category": "Creative",
    "location": "North Shields",
    "instagram": "@CraftyVarie",
    "instagramUrl": "https://www.instagram.com/CraftyVarie/",
    "websiteUrl": "",
    "description": "A ceramicist making one-off, hand-built pieces in a variety of clays.",
    "featured": false
  }
];
