// @ts-expect-error Generated by the OpenNext build.
import openNextHandler from "./.open-next/worker.js";

export default {
  async fetch(request, env, ctx) {
    const response = await openNextHandler.fetch(request, env, ctx);
    if (!new URL(request.url).hostname.endsWith(".workers.dev")) return response;
    const headers = new Headers(response.headers);
    headers.set("X-Robots-Tag", "noindex, nofollow");
    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers,
    });
  },
  async scheduled(event, env, ctx) {
    const runtimeEnv = env as CloudflareEnv & {
      EXTERNAL_INTEGRATIONS_MODE?: string;
      NETWORK_ADMIN_SECRET: string;
    };
    const londonHour = new Intl.DateTimeFormat("en-GB", {
      timeZone: "Europe/London",
      hour: "2-digit",
      hourCycle: "h23",
    }).format(new Date(event.scheduledTime));
    const rotateFeatured = runtimeEnv.EXTERNAL_INTEGRATIONS_MODE === "live" && event.cron !== "*/10 * * * *" && londonHour === "08";
    const jobTypes = ["mailchimp", "bio", "owner", "email", "sheet"] as const;
    const requests = jobTypes.map((jobType) => {
      const url = new URL("/api/internal/network-jobs", env.APP_URL);
      url.searchParams.set("jobType", jobType);
      url.searchParams.set("limit", jobType === "sheet" ? "3" : "10");
      if (rotateFeatured && jobType === "owner") url.searchParams.set("rotateFeatured", "1");
      return new Request(url, { method: "POST", headers: { Authorization: `Bearer ${runtimeEnv.NETWORK_ADMIN_SECRET}` } });
    });
    ctx.waitUntil(Promise.all(requests.map((request) => openNextHandler.fetch(request, env, ctx))).then(() => undefined));
  },
} satisfies ExportedHandler<CloudflareEnv>;

// @ts-expect-error Generated by the OpenNext build.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
