// @ts-expect-error Generated by the OpenNext build.
import openNextHandler from "./.open-next/worker.js";

export default {
  async fetch(request, env, ctx) {
    const response = await openNextHandler.fetch(request, env, ctx);
    if (!new URL(request.url).hostname.endsWith(".workers.dev")) return response;
    const headers = new Headers(response.headers);
    headers.set("X-Robots-Tag", "noindex, nofollow");
    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers,
    });
  },
  async scheduled(event, env, ctx) {
    const runtimeEnv = env as CloudflareEnv & {
      EXTERNAL_INTEGRATIONS_MODE?: string;
      NETWORK_ADMIN_SECRET: string;
    };
    const londonHour = new Intl.DateTimeFormat("en-GB", {
      timeZone: "Europe/London",
      hour: "2-digit",
      hourCycle: "h23",
    }).format(new Date(event.scheduledTime));
    const rotateFeatured = runtimeEnv.EXTERNAL_INTEGRATIONS_MODE === "live" && event.cron !== "*/10 * * * *" && londonHour === "08";
    const url = new URL("/api/internal/network-jobs", env.APP_URL);
    if (rotateFeatured) url.searchParams.set("rotateFeatured", "1");
    const request = new Request(url, {
      method: "POST",
      headers: { Authorization: `Bearer ${runtimeEnv.NETWORK_ADMIN_SECRET}` },
    });
    ctx.waitUntil(openNextHandler.fetch(request, env, ctx));
  },
} satisfies ExportedHandler<CloudflareEnv>;

// @ts-expect-error Generated by the OpenNext build.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
