// @ts-expect-error Generated by the OpenNext build.
import openNextHandler from "./.open-next/worker.js";

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    let response: Response;

    if (request.method === "GET" && url.pathname === "/sitemap.xml") {
      const cache = await caches.open("nami-sitemap");
      const cached = await cache.match(request);
      if (cached) return cached;

      const generated = await openNextHandler.fetch(request, env, ctx);
      if (generated.ok) {
        const body = await generated.arrayBuffer();
        const headers = new Headers(generated.headers);
        headers.set("Cache-Control", "public, max-age=3600, stale-while-revalidate=86400");
        headers.set("Content-Length", String(body.byteLength));
        response = new Response(body, {
          status: generated.status,
          statusText: generated.statusText,
          headers,
        });
        ctx.waitUntil(cache.put(request, response.clone()));
      } else {
        response = generated;
      }
    } else {
      response = await openNextHandler.fetch(request, env, ctx);
    }

    if (!url.hostname.endsWith(".workers.dev")) return response;
    const headers = new Headers(response.headers);
    headers.set("X-Robots-Tag", "noindex, nofollow");
    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers,
    });
  },
  async scheduled(event, env, ctx) {
    const runtimeEnv = env as CloudflareEnv & {
      NETWORK_ADMIN_SECRET: string;
    };
    const londonHour = new Intl.DateTimeFormat("en-GB", {
      timeZone: "Europe/London",
      hour: "2-digit",
      hourCycle: "h23",
    }).format(new Date(event.scheduledTime));
    const proposeFeatured = event.cron !== "*/10 * * * *" && londonHour === "12";
    const jobTypes = ["mailchimp", "bio", "owner", "email", "sheet"] as const;
    const requests = jobTypes.map((jobType) => {
      const url = new URL("/api/internal/network-jobs", env.APP_URL);
      url.searchParams.set("jobType", jobType);
      url.searchParams.set("limit", jobType === "sheet" ? "3" : "10");
      if (proposeFeatured && jobType === "owner") url.searchParams.set("proposeFeatured", "1");
      return new Request(url, { method: "POST", headers: { Authorization: `Bearer ${runtimeEnv.NETWORK_ADMIN_SECRET}` } });
    });
    ctx.waitUntil(Promise.all(requests.map((request) => openNextHandler.fetch(request, env, ctx))).then(() => undefined));
  },
} satisfies ExportedHandler<CloudflareEnv>;

// @ts-expect-error Generated by the OpenNext build.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
