ALTER TABLE network_events ADD COLUMN slug text;
ALTER TABLE network_events ADD COLUMN event_type text NOT NULL DEFAULT 'Other';
ALTER TABLE network_events ADD COLUMN full_description text NOT NULL DEFAULT '';
ALTER TABLE network_events ADD COLUMN format text NOT NULL DEFAULT 'in_person';
ALTER TABLE network_events ADD COLUMN address text NOT NULL DEFAULT '';
ALTER TABLE network_events ADD COLUMN region text NOT NULL DEFAULT 'North East';
ALTER TABLE network_events ADD COLUMN price_type text NOT NULL DEFAULT 'free';
ALTER TABLE network_events ADD COLUMN price_details text NOT NULL DEFAULT '';
ALTER TABLE network_events ADD COLUMN accessibility text NOT NULL DEFAULT '';
ALTER TABLE network_events ADD COLUMN age_guidance text NOT NULL DEFAULT '';
ALTER TABLE network_events ADD COLUMN contact_email text NOT NULL DEFAULT '';
ALTER TABLE network_events ADD COLUMN cover_image_key text;
ALTER TABLE network_events ADD COLUMN cover_image_alt text NOT NULL DEFAULT '';
ALTER TABLE network_events ADD COLUMN admin_feedback text;
ALTER TABLE network_events ADD COLUMN cancelled_at integer;
ALTER TABLE network_events ADD COLUMN featured integer NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX network_events_slug_idx ON network_events(slug);
CREATE INDEX network_events_member_status_idx ON network_events(member_id,status);
CREATE INDEX network_events_type_idx ON network_events(event_type,starts_at);
CREATE TABLE event_revisions (id text PRIMARY KEY NOT NULL,event_id text NOT NULL REFERENCES network_events(id) ON DELETE CASCADE,member_id text NOT NULL REFERENCES members(id) ON DELETE CASCADE,payload text NOT NULL,status text NOT NULL DEFAULT 'pending',admin_feedback text,submitted_at integer NOT NULL DEFAULT (unixepoch()*1000),reviewed_at integer,reviewer_id text);
CREATE INDEX event_revisions_event_status_idx ON event_revisions(event_id,status);
CREATE TABLE event_sheet_sync_jobs (id text PRIMARY KEY NOT NULL,event_id text NOT NULL REFERENCES network_events(id) ON DELETE CASCADE,status text NOT NULL DEFAULT 'pending',attempts integer NOT NULL DEFAULT 0,next_attempt_at integer NOT NULL DEFAULT (unixepoch()*1000),last_error text,completed_at integer,created_at integer NOT NULL DEFAULT (unixepoch()*1000),updated_at integer NOT NULL DEFAULT (unixepoch()*1000));
CREATE INDEX event_sheet_sync_pending_idx ON event_sheet_sync_jobs(status,next_attempt_at);
CREATE TABLE event_analytics (id text PRIMARY KEY NOT NULL,event_id text,event_type text NOT NULL,anonymous_session_id text NOT NULL DEFAULT '',metadata text NOT NULL DEFAULT '{}',created_at integer NOT NULL DEFAULT (unixepoch()*1000));
CREATE INDEX event_analytics_created_idx ON event_analytics(event_type,created_at);
